# Generated by Django 2.2.5 on 2021-09-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210923_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cocation',
            new_name='location',
        ),
    ]
