# Generated by Django 2.2.5 on 2021-09-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210923_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='clenliness',
            new_name='cleanliness',
        ),
    ]
